name: Contexts testing

# comment push, pull_request→pull_request
on: [pull_request]

jobs:
  funtions:
   runs-on: ubuntu-20.04
   steps:
     - name: dump
       run: |
         echo ${{ contains( 'hello','ll' ) }}
         echo ${{ startsWith( 'hello','he' ) }}
         echo ${{ endsWith( 'hello','lo' ) }}
         echo ${{ format( 'Hello {0} {1} {2}','World', '!', '!' ) }}

  dump_contexts_to_log:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
        continue-on-error: true
      - name: Dump job context
        if: failure()
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        if: always()
        run: echo '${{ toJSON(steps) }}'
        timeout-minutes: 360
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'