name: Container

on: push

jobs:
  docker-steps:
    runs-on: ubuntu-20.04
    container: 
      image: node:19.0.0-alpine3.15
    steps:
      - name: Log node version
        run: node -v
      - name: Step with docker
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: 'bin/echo'
          args: 'Hello World'
      - name: Log node version
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: 'bin/echo'
          args: 'Hello World'


      #options:
      #volumes
      #ports:
      #  - 