name: Container

on: push

jobs:
  node-docker:
    runs-on: ubuntu-20.04
    container: 
      image: node:19.0.0-alpine3.15
    steps:
      - name: Log node version
        run: |
          node -v
          cat /etc/os-release

      #options:
      #volumes
      #ports:
      #  - 