name: Matrix

on: push

jobs:
  node-version:
    runs-on: ubuntu-20.04
    steps:
      - name: Log node node-version
        run: node -v
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Log node node-version
        run: node -v
